parameters:
    volleyball.listener.core.class: Volleyball\Bundle\CoreBundle\Listener\UtilityListener
    
    volleyball.menu.builder.class: Volleyball\Bundle\CoreBundle\Menu\MenuBuilder
    volleyball.menu.main.class: Knp\Menu\MenuItem
    volleyball.menu.nonauth.class: Knp\Menu\MenuItem
    volleyball.menu.voter.request.class: Volleyball\Bundle\CoreBundle\Menu\RequestVoter
    
    volleyball.inflector.class: Volleyball\Bundle\CoreBundle\Inflector\Inflector
    
    volleyball.controller.core.class: Volleyball\Bundle\CoreBundle\Controller\UtilityController
    
    volleyball.dashboard.widget_manager.class: Volleyball\Bundle\CoreBundle\Manager\WidgetManager
        
services:
    volleyball.listener.core:
        class: %volleyball.listener.core.class%
        tags: [{ name: kernel.event_listener, event: kernel.request, method: onKernelRequest }]
        arguments: [ @service_container ]
    
    volleyball.menu.builder:
        class: %volleyball.menu.builder.class%
        arguments: ["@knp_menu.factory", "@security.context", "@translator"]
    volleyball.menu.main:
        class: %volleyball.menu.main.class%
        factory_service: volleyball.menu.builder
        factory_method: createMainMenu
        arguments: [ "@request" ]
        scope: request
        tags: [{ name: knp_menu.menu, alias: main }]
    volleyball.menu.nonauth:
        class: %volleyball.menu.nonauth.class%
        factory_service: volleyball.menu.builder
        factory_method: createNonAuthMenu
        arguments: [ "@request" ]
        scope: request
        tags: [{ name: knp_menu.menu, alias: nonauth }]          
    volleyball.menu.voter.request:
        class: %volleyball.menu.voter.request.class%
        arguments: [ "@service_container" ]
        tags: [{ name: knp_menu.voter }]
            
    volleyball.inflector: 
        class: %volleyball.inflector.class%
    
    volleyball.controller.core:
        class: "%volleyball.controller.core.class%"
        arguments: [ "@sylius.controller.configuration_factory" ]

    volleyball.dashboard.widget_manager:
        class: %volleyball.dashboard.widget_manager.class%
        arguments: [ "@service_container" ]